# npm install -g json
# yarn
# cd node_modules\react-native-obfuscating-transformer
# json -I -f package.json -e "this.dependencies['javascript-obfuscator']='1.3.0'"
# rmdir -r node_modules
# npm install
# cd ../../
# cd android
# ./gradlew assembleEnvironmentTestingRelease
name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x


    - run: |
          npm install -g json
          yarn
         # cd node_modules/react-native-obfuscating-transformer
         # json -I -f package.json -e "this.dependencies['javascript-obfuscator']='1.3.0'"
         # rm -r node_modules
         # npm install
         # cd ../../
          
    -  name: Cache npm dependencies
       uses: actions/cache@v2
       with:
         path: '~/.npm'
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
           ${{ runner.os }}-node-
           
    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        
    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
          
    - name: Build Android apk (debug)
      run: | 
          cd android && chmod +x ./gradlew
          ./gradlew assembleDebug -Dorg.gradle.logging.level=info
      #working-directory: android
      

    -  uses: actions/upload-artifact@v2
       with:
          name: android-apk
          path: '**/*.apk'
